name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: pytest tests

    deploy:
        needs: test # Run this job only if tests pass
        runs-on: ubuntu-latest

        steps:
            - name: Log in to Amazon ECR
              run: |
                  aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com

            - name: Build and push Docker image
              run: |
                  docker build -t fastapi-ml .
                  docker tag fastapi-ml:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/fastapi-ml:latest
                  docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/fastapi-ml:latest

            - name: Deploy to AWS Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v22
              with:
                  application_name: "fastapi-ml"
                  environment_name: "fastapi-env"
                  version_label: ${{ github.sha }}
                  region: "us-east-1"
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
